# Generated by Django 3.2.13 on 2023-12-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=240, verbose_name='Handle')),
                ('youtube_url', models.URLField(max_length=240, verbose_name='YoutubeUrl')),
                ('soundcloud_url', models.URLField(max_length=240, verbose_name='SoundcloudUrl')),
            ],
        ),
    ]
