# Generated by Django 3.2.13 on 2024-01-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_socials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Platform Name')),
                ('base_url', models.URLField(verbose_name='Base URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='social',
            name='soundcloud_url',
        ),
        migrations.RemoveField(
            model_name='social',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='social',
            name='soundcloud_user_id',
            field=models.IntegerField(default=None, verbose_name='SoundcloudUserID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SocialPlatformMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_identifier', models.CharField(max_length=100, verbose_name='Platform ID')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_socials.socialplatform')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_socials.social')),
            ],
        ),
        migrations.AddField(
            model_name='social',
            name='platforms',
            field=models.ManyToManyField(through='api_socials.SocialPlatformMapping', to='api_socials.SocialPlatform'),
        ),
    ]
