# Generated by Django 3.2.13 on 2024-01-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_socials', '0002_auto_20240103_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='soundcloud_user_id',
            field=models.IntegerField(verbose_name='SoundcloudUserID'),
        ),
    ]
