# Generated by Django 3.2.13 on 2024-01-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_socials', '0003_alter_social_soundcloud_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='soundcloud_user_id',
        ),
    ]
