# Generated by Django 3.2.13 on 2024-01-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_socials', '0004_auto_20240103_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatformmapping',
            name='platform_url',
            field=models.CharField(default='', max_length=100, verbose_name='Platform URL'),
            preserve_default=False,
        ),
    ]
