# Generated by Django 3.2.13 on 2023-12-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_playlists.playlist')),
            ],
        ),
    ]
